from src.models.models import Employee, Project

# NOTE: this is static sample data living in process memory.
# Swap PROJECTS / EMPLOYEES for a DB-backed repository later without
# touching main.py, since the routes only depend on these two lists.

PROJECTS: list[Project] = [
    Project(
        id="proj-001",
        name="Smart Water Monitoring Platform",
        description="IoT-based water quality monitoring with anomaly detection.",
        client="AquaTun",
        startDate="2025-02-01",
        endDate="2025-06-15",
        status="completed",
        technologies=["FastAPI", "RabbitMQ", "Redis", "LSTM", "Docker"],
        teamMembers=["emp-001", "emp-002", "emp-005"],
    ),
    Project(
        id="proj-002",
        name="Tender Automation Pipeline",
        description="LangGraph-based agent pipeline for tender eligibility and drafting.",
        client="ZetaBox Internal",
        startDate="2026-04-01",
        endDate=None,
        status="in_progress",
        technologies=["LangGraph", "Python", "FastAPI", "MCP"],
        teamMembers=["emp-001", "emp-004"],
    ),
    Project(
        id="proj-003",
        name="Industrial Equipment Marketplace",
        description="B2B marketplace for industrial equipment and procurement.",
        client="Internal Venture",
        startDate="2024-09-01",
        endDate=None,
        status="planned",
        technologies=["Node.js", "Express", "PostgreSQL", "Docker"],
        teamMembers=["emp-002", "emp-006"],
    ),
    Project(
        id="proj-004",
        name="ERP Manufacturing Suite",
        description="Inventory, HR, accounting, and production planning platform.",
        client="MetalWorks Tunisia",
        startDate="2025-09-15",
        endDate=None,
        status="in_progress",
        technologies=["FastAPI", "PostgreSQL", "Redis", "React"],
        teamMembers=["emp-002", "emp-003", "emp-006"],
    ),
    Project(
        id="proj-005",
        name="Customer Support AI Assistant",
        description="LLM-powered multilingual support chatbot.",
        client="Telecom Plus",
        startDate="2026-01-10",
        endDate=None,
        status="in_progress",
        technologies=["Python", "LangGraph", "OpenAI", "FastAPI"],
        teamMembers=["emp-001", "emp-004", "emp-007"],
    ),
    Project(
        id="proj-006",
        name="Logistics Route Optimizer",
        description="Optimization engine for fleet routing and delivery planning.",
        client="Express Logistics",
        startDate="2024-03-01",
        endDate="2025-01-20",
        status="completed",
        technologies=["Python", "OR-Tools", "PostgreSQL", "Docker"],
        teamMembers=["emp-003", "emp-005"],
    ),
    Project(
        id="proj-007",
        name="Cloud Cost Analytics",
        description="Dashboard for cloud resource usage and cost optimization.",
        client="Cloudify",
        startDate="2026-06-01",
        endDate=None,
        status="planned",
        technologies=["FastAPI", "ClickHouse", "Grafana"],
        teamMembers=["emp-004", "emp-005"],
    ),
    Project(
        id="proj-008",
        name="Predictive Maintenance Platform",
        description="Machine learning platform for industrial equipment maintenance.",
        client="FactoryTech",
        startDate="2025-05-01",
        endDate="2026-02-15",
        status="completed",
        technologies=["Python", "TensorFlow", "Kafka", "Docker"],
        teamMembers=["emp-001", "emp-003", "emp-005"],
    ),
]

EMPLOYEES: list[Employee] = [
    Employee(
        id="emp-001",
        firstName="Amine",
        lastName="Jmal",
        position="AI Engineer",
        department="AI Engineering",
        hireDate="2026-02-01",
        skills=["Python", "LangGraph", "FastAPI", "RAG", "Docker"],
        isActive=True,
        yearsOfExperience=3,
        pastProjectIds=["proj-001", "proj-002", "proj-005", "proj-008"],
    ),
    Employee(
        id="emp-002",
        firstName="Sara",
        lastName="Trabelsi",
        position="Senior Backend Engineer",
        department="Engineering",
        hireDate="2023-05-10",
        skills=["Node.js", "PostgreSQL", "Docker", "Redis", "FastAPI"],
        isActive=True,
        yearsOfExperience=6,
        pastProjectIds=["proj-001", "proj-003", "proj-004"],
    ),
    Employee(
        id="emp-003",
        firstName="Youssef",
        lastName="Ben Ali",
        position="Data Engineer",
        department="Data",
        hireDate="2022-11-18",
        skills=["Python", "Airflow", "Kafka", "Spark", "SQL"],
        isActive=True,
        yearsOfExperience=7,
        pastProjectIds=["proj-004", "proj-006", "proj-008"],
    ),
    Employee(
        id="emp-004",
        firstName="Meriem",
        lastName="Ksibi",
        position="Machine Learning Engineer",
        department="AI Engineering",
        hireDate="2024-01-08",
        skills=["PyTorch", "LangChain", "FastAPI", "Python", "LLMs"],
        isActive=True,
        yearsOfExperience=4,
        pastProjectIds=["proj-002", "proj-005", "proj-007"],
    ),
    Employee(
        id="emp-005",
        firstName="Omar",
        lastName="Gharbi",
        position="DevOps Engineer",
        department="Infrastructure",
        hireDate="2021-08-30",
        skills=["Docker", "Kubernetes", "Terraform", "AWS", "Linux"],
        isActive=True,
        yearsOfExperience=8,
        pastProjectIds=["proj-001", "proj-006", "proj-007", "proj-008"],
    ),
    Employee(
        id="emp-006",
        firstName="Nour",
        lastName="Hamdi",
        position="Full Stack Developer",
        department="Engineering",
        hireDate="2025-03-12",
        skills=["React", "TypeScript", "FastAPI", "PostgreSQL"],
        isActive=True,
        yearsOfExperience=3,
        pastProjectIds=["proj-003", "proj-004"],
    ),
    Employee(
        id="emp-007",
        firstName="Karim",
        lastName="Mansouri",
        position="QA Automation Engineer",
        department="Quality Assurance",
        hireDate="2024-06-17",
        skills=["Playwright", "Python", "CI/CD", "API Testing"],
        isActive=True,
        yearsOfExperience=5,
        pastProjectIds=["proj-005"],
    ),
    Employee(
        id="emp-008",
        firstName="Leila",
        lastName="Ben Salem",
        position="UI/UX Designer",
        department="Design",
        hireDate="2023-09-04",
        skills=["Figma", "Design Systems", "User Research", "Prototyping"],
        isActive=False,
        yearsOfExperience=6,
        pastProjectIds=[],
    ),
]
