"""create batch and tender tables

Revision ID: 13f909071fcd
Revises: 
Create Date: 2026-07-26 12:40:46.048936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13f909071fcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('tenders_found_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('run_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('bid_num', sa.String(), nullable=False),
    sa.Column('bid_master_num', sa.String(), nullable=True),
    sa.Column('bid_name_ar', sa.Text(), nullable=True),
    sa.Column('bid_name_fr', sa.Text(), nullable=True),
    sa.Column('bid_name_en', sa.Text(), nullable=True),
    sa.Column('scraped_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'rejected', 'needs_more_data', name='tender_status'), server_default='needs_more_data', nullable=False),
    sa.Column('date_published', sa.Date(), nullable=True),
    sa.Column('final_submission_date', sa.Date(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('general_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lots_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_merged_object', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('proposal_ai_generated', sa.Text(), nullable=True),
    sa.Column('proposal_final', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenders')
    op.drop_table('batches')
    # ### end Alembic commands ###
