"""removed final proposal and added failures fields in batch

Revision ID: 260bb028528b
Revises: 13f909071fcd
Create Date: 2026-08-07 08:36:49.748134

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "260bb028528b"
down_revision: Union[str, Sequence[str], None] = "13f909071fcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "batches",
        sa.Column(
            "tenders_failed_count", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.drop_column("tenders", "proposal_final")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenders",
        sa.Column("proposal_final", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("batches", "tenders_failed_count")
    # ### end Alembic commands ###
